# Generated by Django 2.1.1 on 2018-09-11 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='blog',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
