# Generated by Django 2.1.1 on 2018-09-12 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogApp', '0005_blogmodel_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.BlogModel')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.Choice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
