# Generated by Django 2.1.1 on 2018-09-12 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='blog_model',
            new_name='blog',
        ),
    ]
