# Generated by Django 2.1.3 on 2018-12-08 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BodhiAI_Blog_App', '0002_auto_20181208_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='board',
            new_name='category',
        ),
    ]
