# Generated by Django 2.1.3 on 2018-12-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BodhiAI_Blog_App', '0003_auto_20181208_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Image',
            field=models.ImageField(blank=True, upload_to='Blog_image/'),
        ),
    ]
