# Generated by Django 2.1.3 on 2018-12-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BodhiAI_Blog_App', '0005_auto_20181208_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Image',
            field=models.ImageField(blank=True, upload_to='static/media'),
        ),
    ]
